### ISSUE TITLE
FireAlarm reports closed questions.

### ISSUE THREAD

**Issue by Fortunate-MAN** [SOBotics/FireAlarm#10]
The title explains it. Posting it here as a reminder for myself.

**Comment by NobodyNada** [comment]
IIRC it only does when the question is closed seconds before being reported, because network delay and API caching.

**Comment by Fortunate-MAN** [comment]
@NobodyNada nope. Yesterday it posted a question which was closed one hour before the report. The post it reported was detected after an edit.

**Comment by Fortunate-MAN** [comment]
uh, there seems to be a problem @NobodyNada . I was going to fix this today when I realised in the function `checkAndReportPost` a type `Post` is passed, not `Question`. It surely does not make sense making one more api call, so should I change it such that everywhere `Question` is passed instead of `Post`?

**Comment by NobodyNada** [comment]
@Asish sure!

**Comment by Fortunate-MAN** [comment]
@NobodyNada ok, I'll do that tomorrow or day after.
