### ISSUE TITLE
The bot just leaked its API key

### ISSUE THREAD

**Issue by dorukayhan** [SOBotics/FireAlarm#11]
[This message](http://chat.stackoverflow.com/transcript/message/36456770#36456770) in [FireAlarm Development](http://chat.stackoverflow.com/rooms/123602/firealarm-development) contains the API key of FireAlarm. Is this bad enough to warrant changing the key?

**Comment by NobodyNada** [comment]
No; the API key is not private (you can see it in the code, if you look).
