### ISSUE TITLE
Add a tag blacklist

### ISSUE THREAD

**Issue by NobodyNada** [SOBotics/FireAlarm#18]
Some tags attract almost nothing but bad questions, for example [[appstore-approval]](https://stackoverflow.com/questions/tagged/appstore-approval).  I'm going to add a tag blacklist, so tags like these can be monitored effectively.

**Comment by Fortunate-MAN** [comment]
Looks like [this is done](https://chat.stackoverflow.com/transcript/123602?m=42090637#42090637)?
