### ISSUE TITLE
Add the train wrecker again

### ISSUE THREAD

**Issue by Filnor** [SOBotics/FireAlarm#19]
The train wrecker [was recently removed](https://github.com/SOBotics/FireAlarm/commit/5bb20d7900e3b23d9581029ff46b3dee3463871e), but on SOBotics, it [appears that most users want it back](https://chat.stackoverflow.com/transcript/message/41557719#41557719).

Can we add it back?

**Comment by Fortunate-MAN** [comment]
(Should be) Fixed. https://github.com/SOBotics/FireAlarm/commit/adc7cca038464b29e24d327860a8f66aaa89e7a6

I don't have time to test right now; will do later and close issue.

**Comment by Fortunate-MAN** [comment]
Fix confirmed. https://chat.stackoverflow.com/transcript/message/41563623#41563623

**Comment by danbopes** [comment]
I'm personally against this. It just adds noise in the chat, and with a lot of the other bots, I'm more inclined to ignore the bot with useless functionality like this.

**Comment by Bhargav-Rao** [comment]
I'd rather say that we remove the train wreck for the normal jobs which we do daily, like feedbacks. The #rekdtrain shouldn't fire when we're giving a bunch of feedback to any of the bots, either using the feedback command, or the reply option. Let the train wreck remain when a lot of people say the same general thing. 

The issue which @danbopes is facing is that, they're seeing the #rekdtrain almost daily, at which point the joke becomes annoying.

**Comment by Fortunate-MAN** [comment]
Alright, I'm assuming that no one has an objection with removing the train wrecker for now.

@Bhargav-Rao that seems to be a nice idea; could you open an issue for that? I'll try to do that when I can.
