### ISSUE TITLE
Remove trailing backslashes from question titles

### ISSUE THREAD

**Issue by ArcticEcho** [SOBotics/FireAlarm#22]
Today we had a [report](https://chat.stackoverflow.com/transcript/111347?m=42207397#42207397) where the question's title ended with a backslash (\\), this caused the link markdown to be escaped and thus broke the link:

> [ [FireAlarm-Swift](//stackapps.com/q/7183) ] [tag:php] Potentially bad question [Undefined index: files in C:\](//stackoverflow.com/q/49947530)

The question's title:

> Undefined index: files in C:\

Sadly it seems you can't escape backslashes in chat, so they will have to be removed.

**Comment by Fortunate-MAN** [comment]
*Should* be fixed. I couldn't find a post with a trailing backslash and the report specified has been deleted. At least the change doesn't wreck reports without a backslash. Thanks for reporting this!
